//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiHiago.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teste
    {
        public int id { get; set; }
        public string cpf { get; set; }
        public string rg { get; set; }
        public string nome { get; set; }
    }
}
